apiVersion: v1
kind: Service
metadata:
  name: ha-app-service
spec:
  selector:
    app: ha-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-app-deployment
spec:
  selector:
    matchLabels:
      app: ha-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ha-app
    spec:
      containers:
        - name: ha-app
          image: steffenp123/ha-app:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ha-app-config-map
                  key: DATABASE_URL